"""Add avatar and robot_name columns to user table

Revision ID: 636107df93dd
Revises: 
Create Date: 2025-05-06 16:29:59.009965

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '636107df93dd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('face_login_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('location', sa.String(length=128), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('emotion', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('robot_name', sa.String(length=32), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('robot_name')
        batch_op.drop_column('avatar')

    op.drop_table('face_login_log')
    # ### end Alembic commands ###
